# Generated by Django 4.2.7 on 2024-10-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del usuario')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('imgPerfil', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
