# Generated by Django 4.2.7 on 2024-10-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imgPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='imgPerfil/'),
        ),
    ]
