# Generated by Django 4.2.7 on 2024-10-18 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0002_alter_usuario_imgperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.CharField(choices=[('adm', 'administrador'), ('usu', 'usuario'), ('tec', 'tecnico')], default='usu', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='roles del usuario'),
        ),
    ]
