# Generated by Django 4.2.7 on 2024-10-21 21:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0003_usuario_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del grupo')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del grupo')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del dispositivo')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='primeraApp.casa', verbose_name='Grupo familiar')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.CharField(default='usu', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='roles del usuario'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='primeraApp.casa')),
            ],
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Identificador del medidor')),
                ('casa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medidor', to='primeraApp.casa', verbose_name='Grupo familiar vinculado')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField(verbose_name='Consumo en kWh')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='primeraApp.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('consumo_total', models.FloatField(verbose_name='Consumo total diario en kWh')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='primeraApp.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='primeraApp.medidor', verbose_name='Medidor vinculado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primeraApp.casa', verbose_name='Grupo Familiar'),
        ),
    ]
