# Generated by Django 5.1 on 2024-10-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0005_alter_casa_options_alter_dispositivo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='direccion',
        ),
    ]
