# Generated by Django 5.1 on 2024-10-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0006_remove_casa_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de dispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de dispositivo'),
        ),
    ]
